%%{init: { 
  "sequence": { 
    "mirrorActors": false, 
    "actorLineAlignment": "not-same", 
    "messageMargin": 30, 
    "boxMargin": 10, 
    "bottomMargin": 5
  },
  "themeVariables": {
    "actorBkg": "#641515ff",
    "actorBorder": "#999999"
  }
}}%%
sequenceDiagram
    autonumber
    participant Browser as "User Browser"
    participant Flask as "Flask Application<br/>Server"
    participant Jinja as "Jinja Variable"

    Browser->>Flask: GET /update-form
    Flask->>Jinja: Registers csrf_token
    Flask->>Jinja: Evaluates token
    Jinja-->>Flask: Returns raw token
    Flask-->>Browser: HTML Page with Token
